yolo_usb_detector:
  ros__parameters:
    camera_backend: realsense
    realsense_serial: ""
    camera_device: /dev/video4
    camera_index: 0
    camera_width: 640
    camera_height: 480
    camera_fps: 30
    use_mjpeg: true
    depth_window_size: 7
    min_depth: 0.2
    max_depth: 8.0

    input_size: 320
    confidence_threshold: 0.5
    nms_threshold: 0.45
    target_class_id: 0
    target_class_name: target
    inference_frequency: 10.0
    inference_threads: 4

    show_image: true
    frame_id: usb_camera_pixel
    output_topic: /yolo/target_pixel
    camera_optical_frame_id: camera_color_optical_frame
    point_3d_topic: /yolo/target_point_3d
